export const bookGenres = [
  'Fiction',
  'Non-Fiction',
  'Romance',
  'Mystery/Thriller',
  'Science Fiction',
  'Fantasy',
  'Horror',
  'Historical',
  "Children's and Young Adult",
  'Poetry',
  'Drama/Play',
  'Comics/Graphic Novels',
  'Adventure',
  'Satire/Humor',
  'Western',
  'Religious/Spiritual',
  'War/Military',
  'Biography/Autobiography',
  'Social Science',
  'Dystopian',
];
